# Generated by Django 5.2.8 on 2026-05-04 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of what this lesson covers', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Make this lesson visible to students', verbose_name='published'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF notes or slides for students to download', null=True, upload_to='lessons/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF notes/document'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Estimated time to complete this lesson', verbose_name='duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Allow viewing without enrollment', verbose_name='free preview'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('youtube', 'YouTube Video'), ('document', 'Document/PDF'), ('quiz', 'Quiz')], default='youtube', max_length=20, verbose_name='lesson type'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, help_text='Written lesson content (optional)', verbose_name='text notes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (or use YouTube URL instead)', null=True, upload_to='lessons/videos/', verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste YouTube video link (e.g., https://www.youtube.com/watch?v=...)', verbose_name='YouTube URL'),
        ),
    ]
