# Generated by Django 6.0.4 on 2026-05-29 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_pattern', models.CharField(max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('intent', models.CharField(choices=[('courses', 'Courses'), ('payments', 'Payments'), ('enrollment', 'Enrollment'), ('certificates', 'Certificates'), ('platform', 'Platform Help'), ('instructor', 'Instructor'), ('general', 'General')], max_length=50)),
                ('response_variations', models.JSONField(default=list)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'knowledge entry',
                'verbose_name_plural': 'knowledge entries',
                'ordering': ['-success_count'],
            },
        ),
        migrations.CreateModel(
            name='ThinkingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50)),
                ('step_order', models.IntegerField(default=1)),
                ('message', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField(default=800)),
            ],
            options={
                'verbose_name': 'thinking step',
                'verbose_name_plural': 'thinking steps',
                'ordering': ['intent', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=100)),
                ('strategy_used', models.CharField(blank=True, max_length=50)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat interaction',
                'verbose_name_plural': 'chat interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent_detected', '-created_at'], name='chatbot_cha_intent__87cf2e_idx'), models.Index(fields=['was_helpful'], name='chatbot_cha_was_hel_4b782d_idx')],
            },
        ),
    ]
